# from datasets import load_dataset
# from matplotlib import pyplot as plt
#
# ds = load_dataset("lambdalabs/pokemon-blip-captions", split="train")
# sample = ds[0]
#
# plt.figure('image')
# a = sample["image"]
# print(a.shape)
# plt.imshow(a)
# plt.show()

import torch

sd = torch.load("models/ldm/text2img-large/model.ckpt", map_location="cpu")
if "state_dict" in list(sd.keys()):
    sd = sd["state_dict"]

keys = list(sd.keys())
print(keys)

"""
输出结果
['betas', 'alphas_cumprod', 'alphas_cumprod_prev', 'sqrt_alphas_cumprod', 'sqrt_one_minus_alphas_cumprod', 
'log_one_minus_alphas_cumprod', 'sqrt_recip_alphas_cumprod', 'sqrt_recipm1_alphas_cumprod', 'posterior_variance', 
'posterior_log_variance_clipped', 'posterior_mean_coef1', 'posterior_mean_coef2', 

'model.diffusion_model.time_embed.0.weight', 'model.diffusion_model.time_embed.0.bias', 
'model.diffusion_model.time_embed.2.weight', 'model.diffusion_model.time_embed.2.bias', 
'model.diffusion_model.input_blocks.0.0.weight', 'model.diffusion_model.input_blocks.0.0.bias', 
'model.diffusion_model.input_blocks.1.0.in_layers.0.weight', 'model.diffusion_model.input_blocks.1.0.in_layers.0.bias', 
'model.diffusion_model.input_blocks.1.0.in_layers.2.weight', 'model.diffusion_model.input_blocks.1.0.in_layers.2.bias', 
'model.diffusion_model.input_blocks.1.0.emb_layers.1.weight', 'model.diffusion_model.input_blocks.1.0.emb_layers.1.bias', 
'model.diffusion_model.input_blocks.1.0.out_layers.0.weight', 'model.diffusion_model.input_blocks.1.0.out_layers.0.bias', 
'model.diffusion_model.input_blocks.1.0.out_layers.3.weight', 'model.diffusion_model.input_blocks.1.0.out_layers.3.bias', 
'model.diffusion_model.input_blocks.1.1.norm.weight', 'model.diffusion_model.input_blocks.1.1.norm.bias', 
'model.diffusion_model.input_blocks.1.1.proj_in.weight', 'model.diffusion_model.input_blocks.1.1.proj_in.bias', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_k.weight', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_out.0.weight', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.0.proj.weight', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.0.proj.bias', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.2.weight', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.2.bias', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_q.weight', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_v.weight', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_out.0.bias', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm1.weight', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm1.bias', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm2.weight', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm2.bias', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm3.weight', 
'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm3.bias', 
'model.diffusion_model.input_blocks.1.1.proj_out.weight', 'model.diffusion_model.input_blocks.1.1.proj_out.bias', 
'model.diffusion_model.input_blocks.2.0.in_layers.0.weight', 'model.diffusion_model.input_blocks.2.0.in_layers.0.bias', 
'model.diffusion_model.input_blocks.2.0.in_layers.2.weight', 'model.diffusion_model.input_blocks.2.0.in_layers.2.bias', 
'model.diffusion_model.input_blocks.2.0.emb_layers.1.weight', 'model.diffusion_model.input_blocks.2.0.emb_layers.1.bias', 
'model.diffusion_model.input_blocks.2.0.out_layers.0.weight', 'model.diffusion_model.input_blocks.2.0.out_layers.0.bias', 
'model.diffusion_model.input_blocks.2.0.out_layers.3.weight', 'model.diffusion_model.input_blocks.2.0.out_layers.3.bias', 
'model.diffusion_model.input_blocks.2.1.norm.weight', 'model.diffusion_model.input_blocks.2.1.norm.bias', 
'model.diffusion_model.input_blocks.2.1.proj_in.weight', 'model.diffusion_model.input_blocks.2.1.proj_in.bias', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_k.weight', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_out.0.weight', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.0.proj.weight', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.0.proj.bias', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.2.weight', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.2.bias', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_q.weight', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_v.weight', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_out.0.bias', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm1.weight', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm1.bias', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm2.weight', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm2.bias', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm3.weight', 
'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm3.bias', 
'model.diffusion_model.input_blocks.2.1.proj_out.weight', 
'model.diffusion_model.input_blocks.2.1.proj_out.bias', 'model.diffusion_model.input_blocks.3.0.op.weight', 
'model.diffusion_model.input_blocks.3.0.op.bias', 'model.diffusion_model.input_blocks.4.0.in_layers.0.weight', 
'model.diffusion_model.input_blocks.4.0.in_layers.0.bias', 'model.diffusion_model.input_blocks.4.0.in_layers.2.weight', 
'model.diffusion_model.input_blocks.4.0.in_layers.2.bias', 'model.diffusion_model.input_blocks.4.0.emb_layers.1.weight', 
'model.diffusion_model.input_blocks.4.0.emb_layers.1.bias', 'model.diffusion_model.input_blocks.4.0.out_layers.0.weight', 
'model.diffusion_model.input_blocks.4.0.out_layers.0.bias', 'model.diffusion_model.input_blocks.4.0.out_layers.3.weight', 
'model.diffusion_model.input_blocks.4.0.out_layers.3.bias', 'model.diffusion_model.input_blocks.4.0.skip_connection.weight', 
'model.diffusion_model.input_blocks.4.0.skip_connection.bias', 'model.diffusion_model.input_blocks.4.1.norm.weight', 
'model.diffusion_model.input_blocks.4.1.norm.bias', 'model.diffusion_model.input_blocks.4.1.proj_in.weight', 
'model.diffusion_model.input_blocks.4.1.proj_in.bias', 'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_k.weight', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_out.0.weight', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.0.proj.weight', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.0.proj.bias', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.2.weight', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.2.bias', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_q.weight', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_v.weight', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_out.0.bias', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm1.weight', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm1.bias', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm2.weight', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm2.bias', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm3.weight', 
'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm3.bias', 
'model.diffusion_model.input_blocks.4.1.proj_out.weight', 
'model.diffusion_model.input_blocks.4.1.proj_out.bias', 'model.diffusion_model.input_blocks.5.0.in_layers.0.weight', 
'model.diffusion_model.input_blocks.5.0.in_layers.0.bias', 'model.diffusion_model.input_blocks.5.0.in_layers.2.weight', 
'model.diffusion_model.input_blocks.5.0.in_layers.2.bias', 'model.diffusion_model.input_blocks.5.0.emb_layers.1.weight', 
'model.diffusion_model.input_blocks.5.0.emb_layers.1.bias', 'model.diffusion_model.input_blocks.5.0.out_layers.0.weight', 
'model.diffusion_model.input_blocks.5.0.out_layers.0.bias', 'model.diffusion_model.input_blocks.5.0.out_layers.3.weight', 
'model.diffusion_model.input_blocks.5.0.out_layers.3.bias', 'model.diffusion_model.input_blocks.5.1.norm.weight', 
'model.diffusion_model.input_blocks.5.1.norm.bias', 'model.diffusion_model.input_blocks.5.1.proj_in.weight', 
'model.diffusion_model.input_blocks.5.1.proj_in.bias', 'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_k.weight', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_out.0.weight', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.0.proj.weight', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.0.proj.bias', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.2.weight', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.2.bias', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_q.weight', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_v.weight', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_out.0.bias', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm1.weight', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm1.bias', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm2.weight', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm2.bias', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm3.weight', 
'model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm3.bias', 'model.diffusion_model.input_blocks.5.1.proj_out.weight', 
'model.diffusion_model.input_blocks.5.1.proj_out.bias', 'model.diffusion_model.input_blocks.6.0.op.weight', 
'model.diffusion_model.input_blocks.6.0.op.bias', 'model.diffusion_model.input_blocks.7.0.in_layers.0.weight', 
'model.diffusion_model.input_blocks.7.0.in_layers.0.bias', 'model.diffusion_model.input_blocks.7.0.in_layers.2.weight', 
'model.diffusion_model.input_blocks.7.0.in_layers.2.bias', 'model.diffusion_model.input_blocks.7.0.emb_layers.1.weight', 
'model.diffusion_model.input_blocks.7.0.emb_layers.1.bias', 'model.diffusion_model.input_blocks.7.0.out_layers.0.weight', 
'model.diffusion_model.input_blocks.7.0.out_layers.0.bias', 'model.diffusion_model.input_blocks.7.0.out_layers.3.weight', 
'model.diffusion_model.input_blocks.7.0.out_layers.3.bias', 'model.diffusion_model.input_blocks.7.0.skip_connection.weight', 
'model.diffusion_model.input_blocks.7.0.skip_connection.bias', 'model.diffusion_model.input_blocks.7.1.norm.weight', 
'model.diffusion_model.input_blocks.7.1.norm.bias', 'model.diffusion_model.input_blocks.7.1.proj_in.weight', 
'model.diffusion_model.input_blocks.7.1.proj_in.bias', 'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_k.weight', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_out.0.weight', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.0.proj.weight', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.0.proj.bias', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.2.weight', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.2.bias', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_q.weight', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_v.weight', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_out.0.bias', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm1.weight', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm1.bias', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm2.weight', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm2.bias', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm3.weight', 
'model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm3.bias', 
'model.diffusion_model.input_blocks.7.1.proj_out.weight', 'model.diffusion_model.input_blocks.7.1.proj_out.bias', 
'model.diffusion_model.input_blocks.8.0.in_layers.0.weight', 'model.diffusion_model.input_blocks.8.0.in_layers.0.bias', 
'model.diffusion_model.input_blocks.8.0.in_layers.2.weight', 'model.diffusion_model.input_blocks.8.0.in_layers.2.bias', 
'model.diffusion_model.input_blocks.8.0.emb_layers.1.weight', 'model.diffusion_model.input_blocks.8.0.emb_layers.1.bias', 
'model.diffusion_model.input_blocks.8.0.out_layers.0.weight', 'model.diffusion_model.input_blocks.8.0.out_layers.0.bias', 
'model.diffusion_model.input_blocks.8.0.out_layers.3.weight', 'model.diffusion_model.input_blocks.8.0.out_layers.3.bias', 
'model.diffusion_model.input_blocks.8.1.norm.weight', 'model.diffusion_model.input_blocks.8.1.norm.bias', 
'model.diffusion_model.input_blocks.8.1.proj_in.weight', 'model.diffusion_model.input_blocks.8.1.proj_in.bias', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_k.weight', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_out.0.weight', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.0.proj.weight', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.0.proj.bias', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.2.weight', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.2.bias', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_q.weight', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_v.weight', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_out.0.bias', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm1.weight', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm1.bias', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm2.weight', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm2.bias', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm3.weight', 
'model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm3.bias', 
'model.diffusion_model.input_blocks.8.1.proj_out.weight', 'model.diffusion_model.input_blocks.8.1.proj_out.bias', 
'model.diffusion_model.input_blocks.9.0.op.weight', 'model.diffusion_model.input_blocks.9.0.op.bias', 
'model.diffusion_model.input_blocks.10.0.in_layers.0.weight', 'model.diffusion_model.input_blocks.10.0.in_layers.0.bias', 
'model.diffusion_model.input_blocks.10.0.in_layers.2.weight', 'model.diffusion_model.input_blocks.10.0.in_layers.2.bias', 
'model.diffusion_model.input_blocks.10.0.emb_layers.1.weight', 'model.diffusion_model.input_blocks.10.0.emb_layers.1.bias', 
'model.diffusion_model.input_blocks.10.0.out_layers.0.weight', 'model.diffusion_model.input_blocks.10.0.out_layers.0.bias', 
'model.diffusion_model.input_blocks.10.0.out_layers.3.weight', 'model.diffusion_model.input_blocks.10.0.out_layers.3.bias', 
'model.diffusion_model.input_blocks.11.0.in_layers.0.weight', 'model.diffusion_model.input_blocks.11.0.in_layers.0.bias', 
'model.diffusion_model.input_blocks.11.0.in_layers.2.weight', 'model.diffusion_model.input_blocks.11.0.in_layers.2.bias', 
'model.diffusion_model.input_blocks.11.0.emb_layers.1.weight', 'model.diffusion_model.input_blocks.11.0.emb_layers.1.bias', 
'model.diffusion_model.input_blocks.11.0.out_layers.0.weight', 'model.diffusion_model.input_blocks.11.0.out_layers.0.bias', 
'model.diffusion_model.input_blocks.11.0.out_layers.3.weight', 'model.diffusion_model.input_blocks.11.0.out_layers.3.bias', 
'model.diffusion_model.middle_block.0.in_layers.0.weight', 'model.diffusion_model.middle_block.0.in_layers.0.bias', 
'model.diffusion_model.middle_block.0.in_layers.2.weight', 'model.diffusion_model.middle_block.0.in_layers.2.bias', 
'model.diffusion_model.middle_block.0.emb_layers.1.weight', 'model.diffusion_model.middle_block.0.emb_layers.1.bias', 
'model.diffusion_model.middle_block.0.out_layers.0.weight', 'model.diffusion_model.middle_block.0.out_layers.0.bias', 
'model.diffusion_model.middle_block.0.out_layers.3.weight', 'model.diffusion_model.middle_block.0.out_layers.3.bias', 
'model.diffusion_model.middle_block.1.norm.weight', 'model.diffusion_model.middle_block.1.norm.bias', 
'model.diffusion_model.middle_block.1.proj_in.weight', 'model.diffusion_model.middle_block.1.proj_in.bias', 
'model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_k.weight', 
'model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_out.0.weight', 
'model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_out.0.bias', 'model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.0.proj.weight', 
'model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.0.proj.bias', 'model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.2.weight', 
'model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.2.bias', 'model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_q.weight', 
'model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_k.weight', 'model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_v.weight', 
'model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_out.0.weight', 'model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_out.0.bias', 
'model.diffusion_model.middle_block.1.transformer_blocks.0.norm1.weight', 'model.diffusion_model.middle_block.1.transformer_blocks.0.norm1.bias', 
'model.diffusion_model.middle_block.1.transformer_blocks.0.norm2.weight', 'model.diffusion_model.middle_block.1.transformer_blocks.0.norm2.bias', 
'model.diffusion_model.middle_block.1.transformer_blocks.0.norm3.weight', 'model.diffusion_model.middle_block.1.transformer_blocks.0.norm3.bias', 
'model.diffusion_model.middle_block.1.proj_out.weight', 'model.diffusion_model.middle_block.1.proj_out.bias', 'model.diffusion_model.middle_block.2.in_layers.0.weight', 
'model.diffusion_model.middle_block.2.in_layers.0.bias', 'model.diffusion_model.middle_block.2.in_layers.2.weight', 'model.diffusion_model.middle_block.2.in_layers.2.bias', 
'model.diffusion_model.middle_block.2.emb_layers.1.weight', 'model.diffusion_model.middle_block.2.emb_layers.1.bias', 'model.diffusion_model.middle_block.2.out_layers.0.weight', 
'model.diffusion_model.middle_block.2.out_layers.0.bias', 'model.diffusion_model.middle_block.2.out_layers.3.weight', 'model.diffusion_model.middle_block.2.out_layers.3.bias', 
'model.diffusion_model.output_blocks.0.0.in_layers.0.weight', 'model.diffusion_model.output_blocks.0.0.in_layers.0.bias', 
'model.diffusion_model.output_blocks.0.0.in_layers.2.weight', 'model.diffusion_model.output_blocks.0.0.in_layers.2.bias', 
'model.diffusion_model.output_blocks.0.0.emb_layers.1.weight', 'model.diffusion_model.output_blocks.0.0.emb_layers.1.bias', 
'model.diffusion_model.output_blocks.0.0.out_layers.0.weight', 'model.diffusion_model.output_blocks.0.0.out_layers.0.bias', 
'model.diffusion_model.output_blocks.0.0.out_layers.3.weight', 'model.diffusion_model.output_blocks.0.0.out_layers.3.bias', 
'model.diffusion_model.output_blocks.0.0.skip_connection.weight', 'model.diffusion_model.output_blocks.0.0.skip_connection.bias', 
'model.diffusion_model.output_blocks.1.0.in_layers.0.weight', 'model.diffusion_model.output_blocks.1.0.in_layers.0.bias', 
'model.diffusion_model.output_blocks.1.0.in_layers.2.weight', 
'model.diffusion_model.output_blocks.1.0.in_layers.2.bias', 'model.diffusion_model.output_blocks.1.0.emb_layers.1.weight', 
'model.diffusion_model.output_blocks.1.0.emb_layers.1.bias', 'model.diffusion_model.output_blocks.1.0.out_layers.0.weight', 
'model.diffusion_model.output_blocks.1.0.out_layers.0.bias', 'model.diffusion_model.output_blocks.1.0.out_layers.3.weight', 
'model.diffusion_model.output_blocks.1.0.out_layers.3.bias', 'model.diffusion_model.output_blocks.1.0.skip_connection.weight', 
'model.diffusion_model.output_blocks.1.0.skip_connection.bias', 'model.diffusion_model.output_blocks.2.0.in_layers.0.weight', 
'model.diffusion_model.output_blocks.2.0.in_layers.0.bias', 'model.diffusion_model.output_blocks.2.0.in_layers.2.weight', 
'model.diffusion_model.output_blocks.2.0.in_layers.2.bias', 
'model.diffusion_model.output_blocks.2.0.emb_layers.1.weight', 'model.diffusion_model.output_blocks.2.0.emb_layers.1.bias', 
'model.diffusion_model.output_blocks.2.0.out_layers.0.weight', 'model.diffusion_model.output_blocks.2.0.out_layers.0.bias', 
'model.diffusion_model.output_blocks.2.0.out_layers.3.weight', 'model.diffusion_model.output_blocks.2.0.out_layers.3.bias', 
'model.diffusion_model.output_blocks.2.0.skip_connection.weight', 'model.diffusion_model.output_blocks.2.0.skip_connection.bias', 
'model.diffusion_model.output_blocks.2.1.conv.weight', 'model.diffusion_model.output_blocks.2.1.conv.bias', 'model.diffusion_model.output_blocks.3.0.in_layers.0.weight', 
'model.diffusion_model.output_blocks.3.0.in_layers.0.bias', 'model.diffusion_model.output_blocks.3.0.in_layers.2.weight', 
'model.diffusion_model.output_blocks.3.0.in_layers.2.bias', 'model.diffusion_model.output_blocks.3.0.emb_layers.1.weight', 
'model.diffusion_model.output_blocks.3.0.emb_layers.1.bias', 
'model.diffusion_model.output_blocks.3.0.out_layers.0.weight', 'model.diffusion_model.output_blocks.3.0.out_layers.0.bias', 
'model.diffusion_model.output_blocks.3.0.out_layers.3.weight', 'model.diffusion_model.output_blocks.3.0.out_layers.3.bias', 
'model.diffusion_model.output_blocks.3.0.skip_connection.weight', 'model.diffusion_model.output_blocks.3.0.skip_connection.bias', 
'model.diffusion_model.output_blocks.3.1.norm.weight', 'model.diffusion_model.output_blocks.3.1.norm.bias', 
'model.diffusion_model.output_blocks.3.1.proj_in.weight', 'model.diffusion_model.output_blocks.3.1.proj_in.bias', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_k.weight', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_out.0.weight', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.0.proj.weight', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.0.proj.bias', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.2.weight', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.2.bias', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_q.weight', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_v.weight', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_out.0.bias', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm1.weight', 'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm1.bias', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm2.weight', 'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm2.bias', 
'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm3.weight', 'model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm3.bias', 
'model.diffusion_model.output_blocks.3.1.proj_out.weight', 'model.diffusion_model.output_blocks.3.1.proj_out.bias', 
'model.diffusion_model.output_blocks.4.0.in_layers.0.weight', 'model.diffusion_model.output_blocks.4.0.in_layers.0.bias', 
'model.diffusion_model.output_blocks.4.0.in_layers.2.weight', 
'model.diffusion_model.output_blocks.4.0.in_layers.2.bias', 'model.diffusion_model.output_blocks.4.0.emb_layers.1.weight', 'model.diffusion_model.output_blocks.4.0.emb_layers.1.bias', 
'model.diffusion_model.output_blocks.4.0.out_layers.0.weight', 'model.diffusion_model.output_blocks.4.0.out_layers.0.bias', 
'model.diffusion_model.output_blocks.4.0.out_layers.3.weight', 'model.diffusion_model.output_blocks.4.0.out_layers.3.bias', 
'model.diffusion_model.output_blocks.4.0.skip_connection.weight', 'model.diffusion_model.output_blocks.4.0.skip_connection.bias', 
'model.diffusion_model.output_blocks.4.1.norm.weight', 'model.diffusion_model.output_blocks.4.1.norm.bias', 'model.diffusion_model.output_blocks.4.1.proj_in.weight', 
'model.diffusion_model.output_blocks.4.1.proj_in.bias', 'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_k.weight', 'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_out.0.weight', 'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.0.proj.weight', 'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.0.proj.bias', 
'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.2.weight', 'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.2.bias', 
'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_q.weight', 'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_v.weight', 'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_out.0.bias', 
'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm1.weight', 'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm1.bias', 
'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm2.weight', 'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm2.bias', 
'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm3.weight', 'model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm3.bias', 
'model.diffusion_model.output_blocks.4.1.proj_out.weight', 'model.diffusion_model.output_blocks.4.1.proj_out.bias', 'model.diffusion_model.output_blocks.5.0.in_layers.0.weight', 
'model.diffusion_model.output_blocks.5.0.in_layers.0.bias', 'model.diffusion_model.output_blocks.5.0.in_layers.2.weight', 'model.diffusion_model.output_blocks.5.0.in_layers.2.bias', 
'model.diffusion_model.output_blocks.5.0.emb_layers.1.weight', 
'model.diffusion_model.output_blocks.5.0.emb_layers.1.bias', 'model.diffusion_model.output_blocks.5.0.out_layers.0.weight', 
'model.diffusion_model.output_blocks.5.0.out_layers.0.bias', 'model.diffusion_model.output_blocks.5.0.out_layers.3.weight', 
'model.diffusion_model.output_blocks.5.0.out_layers.3.bias', 'model.diffusion_model.output_blocks.5.0.skip_connection.weight', 
'model.diffusion_model.output_blocks.5.0.skip_connection.bias', 'model.diffusion_model.output_blocks.5.1.norm.weight', 
'model.diffusion_model.output_blocks.5.1.norm.bias', 'model.diffusion_model.output_blocks.5.1.proj_in.weight', 
'model.diffusion_model.output_blocks.5.1.proj_in.bias', 'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_k.weight', 'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_out.0.weight', 'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.0.proj.weight', 
'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.0.proj.bias', 'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.2.weight', 
'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.2.bias', 'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_q.weight', 
'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_v.weight', 'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_out.0.bias', 'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm1.weight', 
'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm1.bias', 'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm2.weight', 
'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm2.bias', 'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm3.weight', 
'model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm3.bias', 'model.diffusion_model.output_blocks.5.1.proj_out.weight', 
'model.diffusion_model.output_blocks.5.1.proj_out.bias', 'model.diffusion_model.output_blocks.5.2.conv.weight', 'model.diffusion_model.output_blocks.5.2.conv.bias', 
'model.diffusion_model.output_blocks.6.0.in_layers.0.weight', 'model.diffusion_model.output_blocks.6.0.in_layers.0.bias', 'model.diffusion_model.output_blocks.6.0.in_layers.2.weight', 
'model.diffusion_model.output_blocks.6.0.in_layers.2.bias', 'model.diffusion_model.output_blocks.6.0.emb_layers.1.weight', 'model.diffusion_model.output_blocks.6.0.emb_layers.1.bias', 
'model.diffusion_model.output_blocks.6.0.out_layers.0.weight', 'model.diffusion_model.output_blocks.6.0.out_layers.0.bias', 'model.diffusion_model.output_blocks.6.0.out_layers.3.weight', 
'model.diffusion_model.output_blocks.6.0.out_layers.3.bias', 'model.diffusion_model.output_blocks.6.0.skip_connection.weight', 
'model.diffusion_model.output_blocks.6.0.skip_connection.bias', 'model.diffusion_model.output_blocks.6.1.norm.weight', 
'model.diffusion_model.output_blocks.6.1.norm.bias', 'model.diffusion_model.output_blocks.6.1.proj_in.weight', 'model.diffusion_model.output_blocks.6.1.proj_in.bias', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_k.weight', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_out.0.weight', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.0.proj.weight', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.0.proj.bias', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.2.weight', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.2.bias', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_q.weight', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_v.weight', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_out.0.bias', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm1.weight', 'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm1.bias', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm2.weight', 'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm2.bias', 
'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm3.weight', 'model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm3.bias', 
'model.diffusion_model.output_blocks.6.1.proj_out.weight', 'model.diffusion_model.output_blocks.6.1.proj_out.bias', 
'model.diffusion_model.output_blocks.7.0.in_layers.0.weight', 'model.diffusion_model.output_blocks.7.0.in_layers.0.bias', 
'model.diffusion_model.output_blocks.7.0.in_layers.2.weight', 
'model.diffusion_model.output_blocks.7.0.in_layers.2.bias', 'model.diffusion_model.output_blocks.7.0.emb_layers.1.weight', 
'model.diffusion_model.output_blocks.7.0.emb_layers.1.bias', 'model.diffusion_model.output_blocks.7.0.out_layers.0.weight', 
'model.diffusion_model.output_blocks.7.0.out_layers.0.bias', 
'model.diffusion_model.output_blocks.7.0.out_layers.3.weight', 'model.diffusion_model.output_blocks.7.0.out_layers.3.bias', 
'model.diffusion_model.output_blocks.7.0.skip_connection.weight', 'model.diffusion_model.output_blocks.7.0.skip_connection.bias', 
'model.diffusion_model.output_blocks.7.1.norm.weight', 'model.diffusion_model.output_blocks.7.1.norm.bias', 'model.diffusion_model.output_blocks.7.1.proj_in.weight', 
'model.diffusion_model.output_blocks.7.1.proj_in.bias', 'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_k.weight', 'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_out.0.weight', 
'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.0.proj.weight', 'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.0.proj.bias', 
'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.2.weight', 'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.2.bias', 
'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_q.weight', 'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_v.weight', 'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_out.0.bias', 'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm1.weight', 
'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm1.bias', 'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm2.weight', 
'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm2.bias', 'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm3.weight', 
'model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm3.bias', 'model.diffusion_model.output_blocks.7.1.proj_out.weight', 
'model.diffusion_model.output_blocks.7.1.proj_out.bias', 'model.diffusion_model.output_blocks.8.0.in_layers.0.weight', 
'model.diffusion_model.output_blocks.8.0.in_layers.0.bias', 
'model.diffusion_model.output_blocks.8.0.in_layers.2.weight', 'model.diffusion_model.output_blocks.8.0.in_layers.2.bias', 
'model.diffusion_model.output_blocks.8.0.emb_layers.1.weight', 'model.diffusion_model.output_blocks.8.0.emb_layers.1.bias', 
'model.diffusion_model.output_blocks.8.0.out_layers.0.weight', 'model.diffusion_model.output_blocks.8.0.out_layers.0.bias', 
'model.diffusion_model.output_blocks.8.0.out_layers.3.weight', 'model.diffusion_model.output_blocks.8.0.out_layers.3.bias', 
'model.diffusion_model.output_blocks.8.0.skip_connection.weight', 'model.diffusion_model.output_blocks.8.0.skip_connection.bias', 
'model.diffusion_model.output_blocks.8.1.norm.weight', 'model.diffusion_model.output_blocks.8.1.norm.bias', 'model.diffusion_model.output_blocks.8.1.proj_in.weight', 
'model.diffusion_model.output_blocks.8.1.proj_in.bias', 'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_k.weight', 'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_out.0.weight', 'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.0.proj.weight', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.0.proj.bias', 'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.2.weight', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.2.bias', 'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_q.weight', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_v.weight', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_out.0.bias', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm1.weight', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm1.bias', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm2.weight', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm2.bias', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm3.weight', 
'model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm3.bias', 
'model.diffusion_model.output_blocks.8.1.proj_out.weight', 'model.diffusion_model.output_blocks.8.1.proj_out.bias', 
'model.diffusion_model.output_blocks.8.2.conv.weight', 'model.diffusion_model.output_blocks.8.2.conv.bias', 
'model.diffusion_model.output_blocks.9.0.in_layers.0.weight', 'model.diffusion_model.output_blocks.9.0.in_layers.0.bias', 
'model.diffusion_model.output_blocks.9.0.in_layers.2.weight', 'model.diffusion_model.output_blocks.9.0.in_layers.2.bias', 
'model.diffusion_model.output_blocks.9.0.emb_layers.1.weight', 'model.diffusion_model.output_blocks.9.0.emb_layers.1.bias', 
'model.diffusion_model.output_blocks.9.0.out_layers.0.weight', 'model.diffusion_model.output_blocks.9.0.out_layers.0.bias', 
'model.diffusion_model.output_blocks.9.0.out_layers.3.weight', 'model.diffusion_model.output_blocks.9.0.out_layers.3.bias', 
'model.diffusion_model.output_blocks.9.0.skip_connection.weight', 
'model.diffusion_model.output_blocks.9.0.skip_connection.bias', 'model.diffusion_model.output_blocks.9.1.norm.weight', 
'model.diffusion_model.output_blocks.9.1.norm.bias', 'model.diffusion_model.output_blocks.9.1.proj_in.weight', 
'model.diffusion_model.output_blocks.9.1.proj_in.bias', 'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_k.weight', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_out.0.weight', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.0.proj.weight', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.0.proj.bias', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.2.weight', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.2.bias', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_q.weight', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_v.weight', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_out.0.bias', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm1.weight', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm1.bias', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm2.weight', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm2.bias', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm3.weight', 
'model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm3.bias', 
'model.diffusion_model.output_blocks.9.1.proj_out.weight', 
'model.diffusion_model.output_blocks.9.1.proj_out.bias', 'model.diffusion_model.output_blocks.10.0.in_layers.0.weight', 
'model.diffusion_model.output_blocks.10.0.in_layers.0.bias', 'model.diffusion_model.output_blocks.10.0.in_layers.2.weight', 
'model.diffusion_model.output_blocks.10.0.in_layers.2.bias', 'model.diffusion_model.output_blocks.10.0.emb_layers.1.weight', 
'model.diffusion_model.output_blocks.10.0.emb_layers.1.bias', 'model.diffusion_model.output_blocks.10.0.out_layers.0.weight', 
'model.diffusion_model.output_blocks.10.0.out_layers.0.bias', 'model.diffusion_model.output_blocks.10.0.out_layers.3.weight', 
'model.diffusion_model.output_blocks.10.0.out_layers.3.bias', 'model.diffusion_model.output_blocks.10.0.skip_connection.weight', 
'model.diffusion_model.output_blocks.10.0.skip_connection.bias', 'model.diffusion_model.output_blocks.10.1.norm.weight', 
'model.diffusion_model.output_blocks.10.1.norm.bias', 'model.diffusion_model.output_blocks.10.1.proj_in.weight', 
'model.diffusion_model.output_blocks.10.1.proj_in.bias', 'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_k.weight', 'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_out.0.weight', 'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.0.proj.weight', 'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.0.proj.bias', 
'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.2.weight', 'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.2.bias', 
'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_q.weight', 'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_v.weight', 'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_out.0.bias', 'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm1.weight', 
'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm1.bias', 'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm2.weight', 
'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm2.bias', 'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm3.weight', 
'model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm3.bias', 'model.diffusion_model.output_blocks.10.1.proj_out.weight', 
'model.diffusion_model.output_blocks.10.1.proj_out.bias', 'model.diffusion_model.output_blocks.11.0.in_layers.0.weight', 
'model.diffusion_model.output_blocks.11.0.in_layers.0.bias', 'model.diffusion_model.output_blocks.11.0.in_layers.2.weight', 
'model.diffusion_model.output_blocks.11.0.in_layers.2.bias', 'model.diffusion_model.output_blocks.11.0.emb_layers.1.weight', 
'model.diffusion_model.output_blocks.11.0.emb_layers.1.bias', 'model.diffusion_model.output_blocks.11.0.out_layers.0.weight', 
'model.diffusion_model.output_blocks.11.0.out_layers.0.bias', 'model.diffusion_model.output_blocks.11.0.out_layers.3.weight', 
'model.diffusion_model.output_blocks.11.0.out_layers.3.bias', 'model.diffusion_model.output_blocks.11.0.skip_connection.weight', 
'model.diffusion_model.output_blocks.11.0.skip_connection.bias', 'model.diffusion_model.output_blocks.11.1.norm.weight', 
'model.diffusion_model.output_blocks.11.1.norm.bias', 'model.diffusion_model.output_blocks.11.1.proj_in.weight', 
'model.diffusion_model.output_blocks.11.1.proj_in.bias', 'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_q.weight', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_k.weight', 'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_v.weight', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_out.0.weight', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_out.0.bias', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.0.proj.weight', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.0.proj.bias', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.2.weight', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.2.bias', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_q.weight', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_k.weight', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_v.weight', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_out.0.weight', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_out.0.bias', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm1.weight', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm1.bias', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm2.weight', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm2.bias', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm3.weight', 
'model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm3.bias', 
'model.diffusion_model.output_blocks.11.1.proj_out.weight', 'model.diffusion_model.output_blocks.11.1.proj_out.bias', 
'model.diffusion_model.out.0.weight', 'model.diffusion_model.out.0.bias', 'model.diffusion_model.out.2.weight', 
'model.diffusion_model.out.2.bias', 
'model_ema.decay', 
'model_ema.num_updates', 
'first_stage_model.encoder.conv_in.weight', 
'first_stage_model.encoder.conv_in.bias', 'first_stage_model.encoder.down.0.block.0.norm1.weight', 
'first_stage_model.encoder.down.0.block.0.norm1.bias', 'first_stage_model.encoder.down.0.block.0.conv1.weight', 
'first_stage_model.encoder.down.0.block.0.conv1.bias', 'first_stage_model.encoder.down.0.block.0.norm2.weight', 
'first_stage_model.encoder.down.0.block.0.norm2.bias', 'first_stage_model.encoder.down.0.block.0.conv2.weight', 
'first_stage_model.encoder.down.0.block.0.conv2.bias', 'first_stage_model.encoder.down.0.block.1.norm1.weight', 
'first_stage_model.encoder.down.0.block.1.norm1.bias', 'first_stage_model.encoder.down.0.block.1.conv1.weight', 
'first_stage_model.encoder.down.0.block.1.conv1.bias', 'first_stage_model.encoder.down.0.block.1.norm2.weight', 
'first_stage_model.encoder.down.0.block.1.norm2.bias', 'first_stage_model.encoder.down.0.block.1.conv2.weight', 
'first_stage_model.encoder.down.0.block.1.conv2.bias', 'first_stage_model.encoder.down.0.downsample.conv.weight', 
'first_stage_model.encoder.down.0.downsample.conv.bias', 'first_stage_model.encoder.down.1.block.0.norm1.weight', 
'first_stage_model.encoder.down.1.block.0.norm1.bias', 'first_stage_model.encoder.down.1.block.0.conv1.weight', 
'first_stage_model.encoder.down.1.block.0.conv1.bias', 'first_stage_model.encoder.down.1.block.0.norm2.weight', 
'first_stage_model.encoder.down.1.block.0.norm2.bias', 'first_stage_model.encoder.down.1.block.0.conv2.weight', 
'first_stage_model.encoder.down.1.block.0.conv2.bias', 
'first_stage_model.encoder.down.1.block.0.nin_shortcut.weight', 'first_stage_model.encoder.down.1.block.0.nin_shortcut.bias', 
'first_stage_model.encoder.down.1.block.1.norm1.weight', 'first_stage_model.encoder.down.1.block.1.norm1.bias', 
'first_stage_model.encoder.down.1.block.1.conv1.weight', 'first_stage_model.encoder.down.1.block.1.conv1.bias', 
'first_stage_model.encoder.down.1.block.1.norm2.weight', 'first_stage_model.encoder.down.1.block.1.norm2.bias', 
'first_stage_model.encoder.down.1.block.1.conv2.weight', 'first_stage_model.encoder.down.1.block.1.conv2.bias', 
'first_stage_model.encoder.down.1.downsample.conv.weight', 'first_stage_model.encoder.down.1.downsample.conv.bias', 
'first_stage_model.encoder.down.2.block.0.norm1.weight', 
'first_stage_model.encoder.down.2.block.0.norm1.bias', 'first_stage_model.encoder.down.2.block.0.conv1.weight', 
'first_stage_model.encoder.down.2.block.0.conv1.bias', 'first_stage_model.encoder.down.2.block.0.norm2.weight', 
'first_stage_model.encoder.down.2.block.0.norm2.bias', 
'first_stage_model.encoder.down.2.block.0.conv2.weight', 'first_stage_model.encoder.down.2.block.0.conv2.bias', 
'first_stage_model.encoder.down.2.block.0.nin_shortcut.weight', 'first_stage_model.encoder.down.2.block.0.nin_shortcut.bias', 
'first_stage_model.encoder.down.2.block.1.norm1.weight', 'first_stage_model.encoder.down.2.block.1.norm1.bias', 
'first_stage_model.encoder.down.2.block.1.conv1.weight', 'first_stage_model.encoder.down.2.block.1.conv1.bias', 
'first_stage_model.encoder.down.2.block.1.norm2.weight', 'first_stage_model.encoder.down.2.block.1.norm2.bias', 
'first_stage_model.encoder.down.2.block.1.conv2.weight', 'first_stage_model.encoder.down.2.block.1.conv2.bias', 
'first_stage_model.encoder.down.2.downsample.conv.weight', 'first_stage_model.encoder.down.2.downsample.conv.bias', 
'first_stage_model.encoder.down.3.block.0.norm1.weight', 'first_stage_model.encoder.down.3.block.0.norm1.bias', 
'first_stage_model.encoder.down.3.block.0.conv1.weight', 
'first_stage_model.encoder.down.3.block.0.conv1.bias', 'first_stage_model.encoder.down.3.block.0.norm2.weight', 
'first_stage_model.encoder.down.3.block.0.norm2.bias', 'first_stage_model.encoder.down.3.block.0.conv2.weight', 
'first_stage_model.encoder.down.3.block.0.conv2.bias', 
'first_stage_model.encoder.down.3.block.1.norm1.weight', 'first_stage_model.encoder.down.3.block.1.norm1.bias', 
'first_stage_model.encoder.down.3.block.1.conv1.weight', 'first_stage_model.encoder.down.3.block.1.conv1.bias', 
'first_stage_model.encoder.down.3.block.1.norm2.weight', 'first_stage_model.encoder.down.3.block.1.norm2.bias', 
'first_stage_model.encoder.down.3.block.1.conv2.weight', 'first_stage_model.encoder.down.3.block.1.conv2.bias', 
'first_stage_model.encoder.mid.block_1.norm1.weight', 'first_stage_model.encoder.mid.block_1.norm1.bias', 
'first_stage_model.encoder.mid.block_1.conv1.weight', 'first_stage_model.encoder.mid.block_1.conv1.bias', 
'first_stage_model.encoder.mid.block_1.norm2.weight', 'first_stage_model.encoder.mid.block_1.norm2.bias', 
'first_stage_model.encoder.mid.block_1.conv2.weight', 'first_stage_model.encoder.mid.block_1.conv2.bias', 
'first_stage_model.encoder.mid.attn_1.norm.weight', 'first_stage_model.encoder.mid.attn_1.norm.bias', 
'first_stage_model.encoder.mid.attn_1.q.weight', 'first_stage_model.encoder.mid.attn_1.q.bias', 'first_stage_model.encoder.mid.attn_1.k.weight', 
'first_stage_model.encoder.mid.attn_1.k.bias', 'first_stage_model.encoder.mid.attn_1.v.weight', 'first_stage_model.encoder.mid.attn_1.v.bias', 
'first_stage_model.encoder.mid.attn_1.proj_out.weight', 'first_stage_model.encoder.mid.attn_1.proj_out.bias', 'first_stage_model.encoder.mid.block_2.norm1.weight', 
'first_stage_model.encoder.mid.block_2.norm1.bias', 'first_stage_model.encoder.mid.block_2.conv1.weight', 'first_stage_model.encoder.mid.block_2.conv1.bias', 
'first_stage_model.encoder.mid.block_2.norm2.weight', 'first_stage_model.encoder.mid.block_2.norm2.bias', 'first_stage_model.encoder.mid.block_2.conv2.weight', 
'first_stage_model.encoder.mid.block_2.conv2.bias', 'first_stage_model.encoder.norm_out.weight', 'first_stage_model.encoder.norm_out.bias', 
'first_stage_model.encoder.conv_out.weight', 'first_stage_model.encoder.conv_out.bias', 'first_stage_model.decoder.conv_in.weight', 
'first_stage_model.decoder.conv_in.bias', 'first_stage_model.decoder.mid.block_1.norm1.weight', 'first_stage_model.decoder.mid.block_1.norm1.bias', 
'first_stage_model.decoder.mid.block_1.conv1.weight', 'first_stage_model.decoder.mid.block_1.conv1.bias', 
'first_stage_model.decoder.mid.block_1.norm2.weight', 'first_stage_model.decoder.mid.block_1.norm2.bias', 
'first_stage_model.decoder.mid.block_1.conv2.weight', 'first_stage_model.decoder.mid.block_1.conv2.bias', 
'first_stage_model.decoder.mid.attn_1.norm.weight', 'first_stage_model.decoder.mid.attn_1.norm.bias', 
'first_stage_model.decoder.mid.attn_1.q.weight', 'first_stage_model.decoder.mid.attn_1.q.bias', 
'first_stage_model.decoder.mid.attn_1.k.weight', 'first_stage_model.decoder.mid.attn_1.k.bias', 'first_stage_model.decoder.mid.attn_1.v.weight', 
'first_stage_model.decoder.mid.attn_1.v.bias', 'first_stage_model.decoder.mid.attn_1.proj_out.weight', 'first_stage_model.decoder.mid.attn_1.proj_out.bias', 
'first_stage_model.decoder.mid.block_2.norm1.weight', 'first_stage_model.decoder.mid.block_2.norm1.bias', 'first_stage_model.decoder.mid.block_2.conv1.weight', 
'first_stage_model.decoder.mid.block_2.conv1.bias', 'first_stage_model.decoder.mid.block_2.norm2.weight', 'first_stage_model.decoder.mid.block_2.norm2.bias', 
'first_stage_model.decoder.mid.block_2.conv2.weight', 'first_stage_model.decoder.mid.block_2.conv2.bias', 
'first_stage_model.decoder.up.0.block.0.norm1.weight', 'first_stage_model.decoder.up.0.block.0.norm1.bias', 
'first_stage_model.decoder.up.0.block.0.conv1.weight', 'first_stage_model.decoder.up.0.block.0.conv1.bias', 
'first_stage_model.decoder.up.0.block.0.norm2.weight', 'first_stage_model.decoder.up.0.block.0.norm2.bias', 
'first_stage_model.decoder.up.0.block.0.conv2.weight', 'first_stage_model.decoder.up.0.block.0.conv2.bias', 
'first_stage_model.decoder.up.0.block.0.nin_shortcut.weight', 'first_stage_model.decoder.up.0.block.0.nin_shortcut.bias', 
'first_stage_model.decoder.up.0.block.1.norm1.weight', 'first_stage_model.decoder.up.0.block.1.norm1.bias', 
'first_stage_model.decoder.up.0.block.1.conv1.weight', 'first_stage_model.decoder.up.0.block.1.conv1.bias', 
'first_stage_model.decoder.up.0.block.1.norm2.weight', 'first_stage_model.decoder.up.0.block.1.norm2.bias', 
'first_stage_model.decoder.up.0.block.1.conv2.weight', 'first_stage_model.decoder.up.0.block.1.conv2.bias', 
'first_stage_model.decoder.up.0.block.2.norm1.weight', 'first_stage_model.decoder.up.0.block.2.norm1.bias', 
'first_stage_model.decoder.up.0.block.2.conv1.weight', 'first_stage_model.decoder.up.0.block.2.conv1.bias', 
'first_stage_model.decoder.up.0.block.2.norm2.weight', 'first_stage_model.decoder.up.0.block.2.norm2.bias', 
'first_stage_model.decoder.up.0.block.2.conv2.weight', 'first_stage_model.decoder.up.0.block.2.conv2.bias', 
'first_stage_model.decoder.up.1.block.0.norm1.weight', 'first_stage_model.decoder.up.1.block.0.norm1.bias', 
'first_stage_model.decoder.up.1.block.0.conv1.weight', 'first_stage_model.decoder.up.1.block.0.conv1.bias', 
'first_stage_model.decoder.up.1.block.0.norm2.weight', 'first_stage_model.decoder.up.1.block.0.norm2.bias', 
'first_stage_model.decoder.up.1.block.0.conv2.weight', 'first_stage_model.decoder.up.1.block.0.conv2.bias', 
'first_stage_model.decoder.up.1.block.0.nin_shortcut.weight', 'first_stage_model.decoder.up.1.block.0.nin_shortcut.bias', 
'first_stage_model.decoder.up.1.block.1.norm1.weight', 'first_stage_model.decoder.up.1.block.1.norm1.bias', 
'first_stage_model.decoder.up.1.block.1.conv1.weight', 'first_stage_model.decoder.up.1.block.1.conv1.bias', 
'first_stage_model.decoder.up.1.block.1.norm2.weight', 'first_stage_model.decoder.up.1.block.1.norm2.bias', 
'first_stage_model.decoder.up.1.block.1.conv2.weight', 
'first_stage_model.decoder.up.1.block.1.conv2.bias', 'first_stage_model.decoder.up.1.block.2.norm1.weight', 
'first_stage_model.decoder.up.1.block.2.norm1.bias', 'first_stage_model.decoder.up.1.block.2.conv1.weight', 
'first_stage_model.decoder.up.1.block.2.conv1.bias', 'first_stage_model.decoder.up.1.block.2.norm2.weight', 
'first_stage_model.decoder.up.1.block.2.norm2.bias', 'first_stage_model.decoder.up.1.block.2.conv2.weight', 
'first_stage_model.decoder.up.1.block.2.conv2.bias', 'first_stage_model.decoder.up.1.upsample.conv.weight', 
'first_stage_model.decoder.up.1.upsample.conv.bias', 'first_stage_model.decoder.up.2.block.0.norm1.weight', 
'first_stage_model.decoder.up.2.block.0.norm1.bias', 'first_stage_model.decoder.up.2.block.0.conv1.weight', 
'first_stage_model.decoder.up.2.block.0.conv1.bias', 'first_stage_model.decoder.up.2.block.0.norm2.weight', 
'first_stage_model.decoder.up.2.block.0.norm2.bias', 'first_stage_model.decoder.up.2.block.0.conv2.weight', 
'first_stage_model.decoder.up.2.block.0.conv2.bias', 'first_stage_model.decoder.up.2.block.1.norm1.weight', 
'first_stage_model.decoder.up.2.block.1.norm1.bias', 'first_stage_model.decoder.up.2.block.1.conv1.weight', 
'first_stage_model.decoder.up.2.block.1.conv1.bias', 'first_stage_model.decoder.up.2.block.1.norm2.weight', 
'first_stage_model.decoder.up.2.block.1.norm2.bias', 'first_stage_model.decoder.up.2.block.1.conv2.weight', 
'first_stage_model.decoder.up.2.block.1.conv2.bias', 'first_stage_model.decoder.up.2.block.2.norm1.weight', 
'first_stage_model.decoder.up.2.block.2.norm1.bias', 'first_stage_model.decoder.up.2.block.2.conv1.weight', 
'first_stage_model.decoder.up.2.block.2.conv1.bias', 'first_stage_model.decoder.up.2.block.2.norm2.weight', 
'first_stage_model.decoder.up.2.block.2.norm2.bias', 'first_stage_model.decoder.up.2.block.2.conv2.weight', 
'first_stage_model.decoder.up.2.block.2.conv2.bias', 'first_stage_model.decoder.up.2.upsample.conv.weight', 
'first_stage_model.decoder.up.2.upsample.conv.bias', 'first_stage_model.decoder.up.3.block.0.norm1.weight', 
'first_stage_model.decoder.up.3.block.0.norm1.bias', 
'first_stage_model.decoder.up.3.block.0.conv1.weight', 'first_stage_model.decoder.up.3.block.0.conv1.bias', 
'first_stage_model.decoder.up.3.block.0.norm2.weight', 'first_stage_model.decoder.up.3.block.0.norm2.bias', 
'first_stage_model.decoder.up.3.block.0.conv2.weight', 'first_stage_model.decoder.up.3.block.0.conv2.bias', 
'first_stage_model.decoder.up.3.block.1.norm1.weight', 'first_stage_model.decoder.up.3.block.1.norm1.bias', 
'first_stage_model.decoder.up.3.block.1.conv1.weight', 'first_stage_model.decoder.up.3.block.1.conv1.bias', 
'first_stage_model.decoder.up.3.block.1.norm2.weight', 'first_stage_model.decoder.up.3.block.1.norm2.bias', 
'first_stage_model.decoder.up.3.block.1.conv2.weight', 'first_stage_model.decoder.up.3.block.1.conv2.bias', 
'first_stage_model.decoder.up.3.block.2.norm1.weight', 'first_stage_model.decoder.up.3.block.2.norm1.bias', 
'first_stage_model.decoder.up.3.block.2.conv1.weight', 'first_stage_model.decoder.up.3.block.2.conv1.bias', 
'first_stage_model.decoder.up.3.block.2.norm2.weight', 'first_stage_model.decoder.up.3.block.2.norm2.bias', 
'first_stage_model.decoder.up.3.block.2.conv2.weight', 'first_stage_model.decoder.up.3.block.2.conv2.bias', 
'first_stage_model.decoder.up.3.upsample.conv.weight', 'first_stage_model.decoder.up.3.upsample.conv.bias', 
'first_stage_model.decoder.norm_out.weight', 'first_stage_model.decoder.norm_out.bias', 'first_stage_model.decoder.conv_out.weight', 
'first_stage_model.decoder.conv_out.bias', 'first_stage_model.quant_conv.weight', 'first_stage_model.quant_conv.bias', 
'first_stage_model.post_quant_conv.weight', 'first_stage_model.post_quant_conv.bias', 
'cond_stage_model.transformer.token_emb.weight', 
'cond_stage_model.transformer.pos_emb.emb.weight', 'cond_stage_model.transformer.attn_layers.layers.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.0.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.0.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.0.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.0.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.0.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.1.0.weight', 'cond_stage_model.transformer.attn_layers.layers.1.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.1.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.1.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.1.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.1.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.2.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.2.0.bias', 'cond_stage_model.transformer.attn_layers.layers.2.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.2.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.2.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.2.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.2.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.3.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.3.0.bias', 'cond_stage_model.transformer.attn_layers.layers.3.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.3.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.3.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.3.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.4.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.4.0.bias', 'cond_stage_model.transformer.attn_layers.layers.4.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.4.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.4.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.4.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.4.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.5.0.weight', 'cond_stage_model.transformer.attn_layers.layers.5.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.5.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.5.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.5.1.net.2.weight', 'cond_stage_model.transformer.attn_layers.layers.5.1.net.2.bias', 
'cond_stage_model.transformer.attn_layers.layers.6.0.weight', 'cond_stage_model.transformer.attn_layers.layers.6.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.6.1.to_q.weight', 'cond_stage_model.transformer.attn_layers.layers.6.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.6.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.6.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.6.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.7.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.7.0.bias', 'cond_stage_model.transformer.attn_layers.layers.7.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.7.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.7.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.7.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.8.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.8.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.8.1.to_q.weight', 'cond_stage_model.transformer.attn_layers.layers.8.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.8.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.8.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.8.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.9.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.9.0.bias', 'cond_stage_model.transformer.attn_layers.layers.9.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.9.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.9.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.9.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.10.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.10.0.bias', 'cond_stage_model.transformer.attn_layers.layers.10.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.10.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.10.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.10.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.10.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.11.0.weight', 'cond_stage_model.transformer.attn_layers.layers.11.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.11.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.11.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.11.1.net.2.weight', 'cond_stage_model.transformer.attn_layers.layers.11.1.net.2.bias', 
'cond_stage_model.transformer.attn_layers.layers.12.0.weight', 'cond_stage_model.transformer.attn_layers.layers.12.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.12.1.to_q.weight', 'cond_stage_model.transformer.attn_layers.layers.12.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.12.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.12.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.12.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.13.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.13.0.bias', 'cond_stage_model.transformer.attn_layers.layers.13.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.13.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.13.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.13.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.14.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.14.0.bias', 'cond_stage_model.transformer.attn_layers.layers.14.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.14.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.14.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.14.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.14.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.15.0.weight', 'cond_stage_model.transformer.attn_layers.layers.15.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.15.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.15.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.15.1.net.2.weight', 'cond_stage_model.transformer.attn_layers.layers.15.1.net.2.bias', 
'cond_stage_model.transformer.attn_layers.layers.16.0.weight', 'cond_stage_model.transformer.attn_layers.layers.16.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.16.1.to_q.weight', 'cond_stage_model.transformer.attn_layers.layers.16.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.16.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.16.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.16.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.17.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.17.0.bias', 'cond_stage_model.transformer.attn_layers.layers.17.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.17.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.17.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.17.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.18.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.18.0.bias', 'cond_stage_model.transformer.attn_layers.layers.18.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.18.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.18.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.18.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.18.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.19.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.19.0.bias', 'cond_stage_model.transformer.attn_layers.layers.19.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.19.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.19.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.19.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.20.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.20.0.bias', 'cond_stage_model.transformer.attn_layers.layers.20.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.20.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.20.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.20.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.20.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.21.0.weight', 'cond_stage_model.transformer.attn_layers.layers.21.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.21.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.21.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.21.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.21.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.22.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.22.0.bias', 'cond_stage_model.transformer.attn_layers.layers.22.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.22.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.22.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.22.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.22.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.23.0.weight', 'cond_stage_model.transformer.attn_layers.layers.23.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.23.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.23.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.23.1.net.2.weight', 'cond_stage_model.transformer.attn_layers.layers.23.1.net.2.bias', 
'cond_stage_model.transformer.attn_layers.layers.24.0.weight', 'cond_stage_model.transformer.attn_layers.layers.24.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.24.1.to_q.weight', 'cond_stage_model.transformer.attn_layers.layers.24.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.24.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.24.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.24.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.25.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.25.0.bias', 'cond_stage_model.transformer.attn_layers.layers.25.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.25.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.25.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.25.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.26.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.26.0.bias', 'cond_stage_model.transformer.attn_layers.layers.26.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.26.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.26.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.26.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.26.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.27.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.27.0.bias', 'cond_stage_model.transformer.attn_layers.layers.27.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.27.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.27.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.27.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.28.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.28.0.bias', 'cond_stage_model.transformer.attn_layers.layers.28.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.28.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.28.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.28.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.28.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.29.0.weight', 'cond_stage_model.transformer.attn_layers.layers.29.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.29.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.29.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.29.1.net.2.weight', 'cond_stage_model.transformer.attn_layers.layers.29.1.net.2.bias', 
'cond_stage_model.transformer.attn_layers.layers.30.0.weight', 'cond_stage_model.transformer.attn_layers.layers.30.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.30.1.to_q.weight', 'cond_stage_model.transformer.attn_layers.layers.30.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.30.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.30.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.30.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.31.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.31.0.bias', 'cond_stage_model.transformer.attn_layers.layers.31.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.31.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.31.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.31.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.32.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.32.0.bias', 'cond_stage_model.transformer.attn_layers.layers.32.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.32.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.32.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.32.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.32.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.33.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.33.0.bias', 'cond_stage_model.transformer.attn_layers.layers.33.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.33.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.33.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.33.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.34.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.34.0.bias', 'cond_stage_model.transformer.attn_layers.layers.34.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.34.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.34.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.34.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.34.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.35.0.weight', 'cond_stage_model.transformer.attn_layers.layers.35.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.35.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.35.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.35.1.net.2.weight', 'cond_stage_model.transformer.attn_layers.layers.35.1.net.2.bias', 
'cond_stage_model.transformer.attn_layers.layers.36.0.weight', 'cond_stage_model.transformer.attn_layers.layers.36.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.36.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.36.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.36.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.36.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.36.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.37.0.weight', 'cond_stage_model.transformer.attn_layers.layers.37.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.37.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.37.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.37.1.net.2.weight', 'cond_stage_model.transformer.attn_layers.layers.37.1.net.2.bias', 
'cond_stage_model.transformer.attn_layers.layers.38.0.weight', 'cond_stage_model.transformer.attn_layers.layers.38.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.38.1.to_q.weight', 'cond_stage_model.transformer.attn_layers.layers.38.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.38.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.38.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.38.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.39.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.39.0.bias', 'cond_stage_model.transformer.attn_layers.layers.39.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.39.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.39.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.39.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.40.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.40.0.bias', 'cond_stage_model.transformer.attn_layers.layers.40.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.40.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.40.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.40.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.40.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.41.0.weight', 'cond_stage_model.transformer.attn_layers.layers.41.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.41.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.41.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.41.1.net.2.weight', 'cond_stage_model.transformer.attn_layers.layers.41.1.net.2.bias', 
'cond_stage_model.transformer.attn_layers.layers.42.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.42.0.bias', 'cond_stage_model.transformer.attn_layers.layers.42.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.42.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.42.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.42.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.42.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.43.0.weight', 'cond_stage_model.transformer.attn_layers.layers.43.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.43.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.43.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.43.1.net.2.weight', 'cond_stage_model.transformer.attn_layers.layers.43.1.net.2.bias', 
'cond_stage_model.transformer.attn_layers.layers.44.0.weight', 'cond_stage_model.transformer.attn_layers.layers.44.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.44.1.to_q.weight', 'cond_stage_model.transformer.attn_layers.layers.44.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.44.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.44.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.44.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.45.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.45.0.bias', 'cond_stage_model.transformer.attn_layers.layers.45.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.45.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.45.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.45.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.46.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.46.0.bias', 'cond_stage_model.transformer.attn_layers.layers.46.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.46.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.46.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.46.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.46.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.47.0.weight', 'cond_stage_model.transformer.attn_layers.layers.47.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.47.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.47.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.47.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.47.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.48.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.48.0.bias', 'cond_stage_model.transformer.attn_layers.layers.48.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.48.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.48.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.48.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.48.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.49.0.weight', 'cond_stage_model.transformer.attn_layers.layers.49.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.49.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.49.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.49.1.net.2.weight', 'cond_stage_model.transformer.attn_layers.layers.49.1.net.2.bias', 
'cond_stage_model.transformer.attn_layers.layers.50.0.weight', 'cond_stage_model.transformer.attn_layers.layers.50.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.50.1.to_q.weight', 'cond_stage_model.transformer.attn_layers.layers.50.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.50.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.50.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.50.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.51.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.51.0.bias', 'cond_stage_model.transformer.attn_layers.layers.51.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.51.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.51.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.51.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.52.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.52.0.bias', 'cond_stage_model.transformer.attn_layers.layers.52.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.52.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.52.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.52.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.52.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.53.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.53.0.bias', 'cond_stage_model.transformer.attn_layers.layers.53.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.53.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.53.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.53.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.54.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.54.0.bias', 'cond_stage_model.transformer.attn_layers.layers.54.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.54.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.54.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.54.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.54.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.55.0.weight', 'cond_stage_model.transformer.attn_layers.layers.55.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.55.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.55.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.55.1.net.2.weight', 'cond_stage_model.transformer.attn_layers.layers.55.1.net.2.bias', 
'cond_stage_model.transformer.attn_layers.layers.56.0.weight', 'cond_stage_model.transformer.attn_layers.layers.56.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.56.1.to_q.weight', 'cond_stage_model.transformer.attn_layers.layers.56.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.56.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.56.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.56.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.57.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.57.0.bias', 'cond_stage_model.transformer.attn_layers.layers.57.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.57.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.57.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.57.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.58.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.58.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.58.1.to_q.weight', 'cond_stage_model.transformer.attn_layers.layers.58.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.58.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.58.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.58.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.59.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.59.0.bias', 'cond_stage_model.transformer.attn_layers.layers.59.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.59.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.59.1.net.2.weight', 'cond_stage_model.transformer.attn_layers.layers.59.1.net.2.bias', 
'cond_stage_model.transformer.attn_layers.layers.60.0.weight', 'cond_stage_model.transformer.attn_layers.layers.60.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.60.1.to_q.weight', 'cond_stage_model.transformer.attn_layers.layers.60.1.to_k.weight', 
'cond_stage_model.transformer.attn_layers.layers.60.1.to_v.weight', 'cond_stage_model.transformer.attn_layers.layers.60.1.to_out.weight', 
'cond_stage_model.transformer.attn_layers.layers.60.1.to_out.bias', 'cond_stage_model.transformer.attn_layers.layers.61.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.61.0.bias', 'cond_stage_model.transformer.attn_layers.layers.61.1.net.0.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.61.1.net.0.0.bias', 'cond_stage_model.transformer.attn_layers.layers.61.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.61.1.net.2.bias', 'cond_stage_model.transformer.attn_layers.layers.62.0.weight', 
'cond_stage_model.transformer.attn_layers.layers.62.0.bias', 'cond_stage_model.transformer.attn_layers.layers.62.1.to_q.weight', 
'cond_stage_model.transformer.attn_layers.layers.62.1.to_k.weight', 'cond_stage_model.transformer.attn_layers.layers.62.1.to_v.weight', 
'cond_stage_model.transformer.attn_layers.layers.62.1.to_out.weight', 'cond_stage_model.transformer.attn_layers.layers.62.1.to_out.bias', 
'cond_stage_model.transformer.attn_layers.layers.63.0.weight', 'cond_stage_model.transformer.attn_layers.layers.63.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.63.1.net.0.0.weight', 'cond_stage_model.transformer.attn_layers.layers.63.1.net.0.0.bias', 
'cond_stage_model.transformer.attn_layers.layers.63.1.net.2.weight', 
'cond_stage_model.transformer.attn_layers.layers.63.1.net.2.bias', 'cond_stage_model.transformer.norm.weight', 
'cond_stage_model.transformer.norm.bias', 
'cond_stage_model.transformer.to_logits.weight', 
'cond_stage_model.transformer.to_logits.bias']

"""